spring:
    application:
        name: bank-transfer-api
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
    sql:
        init:
            schema-locations: classpath:database/schema.sql
            data-locations: classpath:database/data.sql
            mode: always
    jpa:
        open-in-view: on
        defer-datasource-initialization: true
