### Make a transfer request
POST http://localhost:8080/api/transactions/transfer
Content-Type: application/json

{
	"sender_account_number": "ORANJE00001234",
	"recipient_account": "BLU00001234",
	"recipient_bank_code": "BLU",
	"transfer_amount": 10.00,
	"transfer_type": "InstaPay"
}

### Get transaction details
GET http://localhost:8080/api/transactions/00000000-0000-0000-0000-000000000000
